### ISSUE TITLE
Clear errors when match found

### ISSUE THREAD

**Issue by Xowap** [Xowap/typefit#57]
Imagine the following dict:

```yaml
foo:
    bar:
        type: bar

    baz:
        type: baz
```

And the following types:

```python
@dataclass
class Bar:
    type: Literal["bar"]
    val: int

@dataclass
class Baz:
    type: Literal["baz"]
```

Now, even though our `Baz` value is valid, `Bar` isn't and that's causing a display of errors. However, all the would-be-errors from the different union types on `Baz` will still be displayed, even though internally the fit actually happened.
